In [1]:
from futu import *
import pandas_ta as ta
import pandas as pd

import json
import talib

/opt/homebrew/lib/python3.10/site-packages/pandas_ta/__init__.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound

In [2]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', None)

In [3]:
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111)

2025-07-02 10:32:15,276 | 58188 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=1, host=127.0.0.1, port=11111, user_id=11541642

In [193]:
# quote_ctx.close()

In [4]:
watchlists = quote_ctx.get_user_security_group(group_type = UserSecurityGroupType.ALL)

In [5]:
def get_watch_tickers(group_name="特别关注"):
	ret_code, heart_watch_list = quote_ctx.get_user_security(group_name=group_name)

	heart_watch_list = heart_watch_list[heart_watch_list['stock_type'] == 'STOCK']
	heart_watch_list = heart_watch_list[heart_watch_list['code'].str.startswith('HK')]

	watch_code_list = heart_watch_list['code'].tolist()

	return watch_code_list

In [6]:
trd_ctx = OpenSecTradeContext(filter_trdmarket=TrdMarket.HK, host='127.0.0.1', port=11111, security_firm=SecurityFirm.FUTUSECURITIES)

ret, position_df = trd_ctx.position_list_query()

position_tickers = position_df['code'].tolist()

2025-07-02 10:32:22,781 | 58188 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=2, host=127.0.0.1, port=11111, user_id=11541642

In [7]:
display(position_df)

,code,stock_name,position_market,qty,can_sell_qty,cost_price,cost_price_valid,average_cost,diluted_cost,market_val,...,today_buy_qty,today_buy_val,today_pl_val,today_trd_val,today_sell_qty,today_sell_val,position_side,unrealized_pl,realized_pl,currency
0,HK.03690,美团-W,HK,500.0,500.0,132.500,True,132.500,132.500,62300.0,...,0.0,0.0,-350.0,0.0,0.0,0.0,LONG,-3950.0000,0.0000,HKD
1,HK.01788,国泰君安国际,HK,10000.0,10000.0,4.730,True,4.730,4.730,34600.0,...,0.0,0.0,300.0,0.0,0.0,0.0,LONG,-12700.0000,0.0000,HKD
2,HK.01398,工商银行,HK,5000.0,5000.0,6.360,True,6.360,6.360,31650.0,...,5000.0,31800.0,-150.0,31800.0,0.0,0.0,LONG,-150.0000,0.0000,HKD
3,HK.01211,比亚迪股份,HK,1000.0,1000.0,265.600,True,265.600,265.600,121600.0,...,0.0,0.0,-900.0,0.0,0.0,0.0,LONG,-144000.0000,0.0000,HKD
4,HK.00700,腾讯控股,HK,283.0,283.0,62.259,True,267.338,62.259,141783.0,...,0.0,0.0,-566.0,0.0,0.0,0.0,LONG,66126.2635,556180.7365,HKD

In [8]:
ret, hengsheng_df = quote_ctx.get_plate_stock('HK.HSI Constituent Stocks')  # 恒指成分

hengsheng_tickers = hengsheng_df['code'].tolist()

ret, hot_df = quote_ctx.get_plate_stock('HK.LIST1600')
hot_tickers = hot_df['code'].tolist()

In [9]:

# 腾讯，美团，比亚迪，中芯国际
# for ticker_id in ['HK.00700', 'HK.03690', 'HK.01211', 'HK.00981']:
#    message[ticker_id] = process_super_trend(ticker_id=ticker_id)

config_tickers_list = []
config_tickers_list = get_watch_tickers(group_name="特别关注")
config_tickers_list += get_watch_tickers(group_name="港股")
config_tickers_list += get_watch_tickers(group_name="沪深")

config_tickers_list += hengsheng_tickers
config_tickers_list += hot_tickers
config_tickers_list += position_tickers

config_tickers_list = list(set(config_tickers_list))  # 去重

config_tickers = pd.DataFrame({'ticker_id': config_tickers_list})

In [10]:
config_tickers.shape

(509, 1)

In [ ]:
if False:
	_, test_df, _ = quote_ctx.request_history_kline(
		"HK.00700", start='2000-01-01', end='2025-12-31', max_count=10000, session=Session.ALL)
	display(test_df.sort_values(by='time_key', ascending=False).head(10))

,code,name,time_key,open,close,high,low,pe_ratio,turnover_rate,volume,turnover,change_rate,last_close
2462,HK.00700,腾讯控股,2025-07-02 00:00:00,508.0,500.5,508.5,500.0,21.889,0.00088,8020968,4.040888e+09,-0.497018,503.0
2461,HK.00700,腾讯控股,2025-06-30 00:00:00,509.0,503.0,511.5,503.0,21.998,0.00201,18464531,9.333594e+09,-1.949318,513.0
2460,HK.00700,腾讯控股,2025-06-27 00:00:00,512.0,513.0,514.5,510.0,22.461,0.00165,15181667,7.767267e+09,0.000000,513.0
2459,HK.00700,腾讯控股,2025-06-26 00:00:00,512.0,513.0,513.0,507.5,22.461,0.00163,15000643,7.665271e+09,0.097561,512.5
2458,HK.00700,腾讯控股,2025-06-25 00:00:00,512.0,512.5,515.0,508.0,22.439,0.00192,17592461,8.995908e+09,0.588813,509.5
2457,HK.00700,腾讯控股,2025-06-24 00:00:00,508.0,509.5,511.0,504.0,22.308,0.00194,17768858,9.026969e+09,1.091270,504.0
2456,HK.00700,腾讯控股,2025-06-23 00:00:00,498.2,504.0,504.0,494.6,22.067,0.00155,14252887,7.125786e+09,-0.296736,505.5
2455,HK.00700,腾讯控股,2025-06-20 00:00:00,504.5,505.5,505.5,496.0,22.132,0.00225,20622275,1.036414e+10,1.506024,498.0
2454,HK.00700,腾讯控股,2025-06-19 00:00:00,503.0,498.0,506.0,496.0,21.803,0.00211,19387767,9.674346e+09,-1.968504,508.0
2453,HK.00700,腾讯控股,2025-06-18 00:00:00,510.0,508.0,511.0,503.5,22.241,0.00166,15187515,7.682823e+09,-1.071081,513.5

In [30]:
def get_ticker_history(ticker_id):
	output_file = f"./data/{ticker_id}.csv"
	max_date = None
	curr_date = datetime.today().date().strftime('%Y-%m-%d')
	last_date = (datetime.today() - pd.Timedelta(days=1)).date().strftime('%Y-%m-%d')
	curr_hour = datetime.now().hour
	if os.path.isfile(output_file):
		data = pd.read_csv(output_file)
		if not data.empty:
			max_date = data['time_key'].max()
			max_date = pd.to_datetime(max_date).strftime('%Y-%m-%d')
			if (curr_hour > 18 and max_date >= curr_date) or (curr_hour <= 18 and max_date >= last_date):  
				# 18点以后，尝试获取今天的数据,18点之前，尝试获取昨天的数据
				return data

	ret, data, page_req_key = quote_ctx.request_history_kline(
		ticker_id, start='2000-01-01', end='2025-12-31', max_count=10000, session=Session.ALL)
	time.sleep(0.51)   # qps limit 2
	if ret != 0:
		print(f'Error fetching history for {ticker_id}: {data}')
		return None
	
	data.to_csv(output_file, index=False)
	return data

In [31]:
ticker_history = pd.DataFrame({
    key: [] for key in
    ['code', 'name', 'time_key', 'open', 'close', 'high', 'low', 'pe_ratio',
       'turnover_rate', 'volume', 'turnover', 'change_rate', 'last_close']
})

for index, ticker_id in enumerate(config_tickers_list):
    curr_ticker_history = get_ticker_history(ticker_id)
    if curr_ticker_history is not None and not curr_ticker_history.empty:
        ticker_history = pd.concat([ticker_history, curr_ticker_history], axis=0)
        print(f"Processed {ticker_id} {index + 1}/{len(config_tickers_list)}, {curr_ticker_history.shape}, {curr_ticker_history['time_key'].max()}")

Processed HK.01985 1/509, (2044, 13), 2025-06-30 00:00:00
Processed HK.01888 2/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.00101 3/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00570 4/509, (2451, 13), 2025-07-02 00:00:00
Processed HK.06969 5/509, (1223, 13), 2025-07-02 00:00:00
Processed HK.06086 6/509, (241, 13), 2025-07-02 00:00:00
Processed HK.02587 7/509, (123, 13), 2025-07-02 00:00:00
Processed HK.08162 8/509, (2204, 13), 2025-07-02 00:00:00
Processed HK.01911 9/509, (1310, 13), 2025-07-02 00:00:00
Processed HK.02228 10/509, (258, 13), 2025-07-02 00:00:00
Processed HK.02050 11/509, (7, 13), 2025-07-02 00:00:00
Processed HK.00279 12/509, (2025, 13), 2025-07-02 00:00:00
Processed HK.01093 13/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.01428 14/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.01497 15/509, (378, 13), 2025-06-30 00:00:00
Processed HK.02495 16/509, (240, 13), 2025-07-02 00:00:00
Processed HK.03330 17/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01942 18/509, (1275, 13), 2025-07-02 00:00:00
Processed HK.06608 19/509, (1043, 13), 2025-07-02 00:00:00
Processed HK.00941 20/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00823 21/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.02536 22/509, (309, 13), 2025-07-02 00:00:00
Processed HK.06083 23/509, (2113, 13), 2025-07-02 00:00:00
Processed HK.02502 24/509, (372, 13), 2025-07-02 00:00:00
Processed HK.00127 25/509, (2459, 13), 2025-07-02 00:00:00
Processed HK.00328 26/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.01788 27/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.06998 28/509, (1148, 13), 2025-07-02 00:00:00
Processed HK.01310 29/509, (2460, 13), 2025-07-02 00:00:00
Processed HK.01929 30/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01070 31/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.01568 32/509, (2336, 13), 2025-07-02 00:00:00
Processed HK.03958 33/509, (2209, 13), 2025-07-02 00:00:00
Processed HK.02586 34/509, (137, 13), 2025-07-02 00:00:00
Processed HK.09992 35/509, (1117, 13), 2025-07-02 00:00:00
Processed HK.00762 36/509, (2459, 13), 2025-07-02 00:00:00
Processed HK.00806 37/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02521 38/509, (384, 13), 2025-07-02 00:00:00
Processed HK.00123 39/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01530 40/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01338 41/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00788 42/509, (1696, 13), 2025-07-02 00:00:00
Processed HK.01083 43/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02508 44/509, (4, 13), 2025-07-02 00:00:00
Processed HK.01928 45/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00626 46/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.03347 47/509, (1203, 13), 2025-07-02 00:00:00
Processed HK.01951 48/509, (1482, 13), 2025-07-02 00:00:00
Processed HK.01655 49/509, (2002, 13), 2025-07-02 00:00:00
Processed HK.00467 50/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01723 51/509, (1655, 13), 2025-07-02 00:00:00
Processed HK.00325 52/509, (115, 13), 2025-07-02 00:00:00
Processed HK.02589 53/509, (39, 13), 2025-07-02 00:00:00
Processed HK.01499 54/509, (2381, 13), 2025-07-02 00:00:00
Processed HK.03390 55/509, (1281, 13), 2025-07-02 00:00:00
Processed HK.02007 56/509, (2265, 13), 2025-07-02 00:00:00
Processed HK.09911 57/509, (1352, 13), 2025-07-02 00:00:00
Processed HK.00956 58/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01339 59/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.00637 60/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02569 61/509, (64, 13), 2025-07-02 00:00:00
Processed HK.00669 62/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02099 63/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02343 64/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01177 65/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.09959 66/509, (1038, 13), 2025-07-02 00:00:00
Processed HK.01359 67/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.06862 68/509, (1662, 13), 2025-07-02 00:00:00
Processed HK.01801 69/509, (1639, 13), 2025-07-02 00:00:00
Processed HK.03380 70/509, (2389, 13), 2025-07-02 00:00:00
Processed HK.01288 71/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00883 72/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.09663 73/509, (384, 13), 2025-07-02 00:00:00
Processed HK.02423 74/509, (772, 13), 2025-07-02 00:00:00
Processed HK.06682 75/509, (430, 13), 2025-07-02 00:00:00
Processed HK.00887 76/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01855 77/509, (1101, 13), 2025-07-02 00:00:00
Processed HK.02563 78/509, (103, 13), 2025-07-02 00:00:00
Processed HK.01448 79/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.09926 80/509, (1274, 13), 2025-07-02 00:00:00
Processed HK.02217 81/509, (905, 13), 2025-07-02 00:00:00
Processed HK.01209 82/509, (1119, 13), 2025-07-02 00:00:00
Processed HK.02509 83/509, (313, 13), 2025-07-02 00:00:00
Processed HK.02520 84/509, (392, 13), 2025-06-30 00:00:00
Processed HK.03988 85/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01952 86/509, (1160, 13), 2025-07-02 00:00:00
Processed HK.06878 87/509, (2327, 13), 2025-03-31 00:00:00
Processed HK.01606 88/509, (2207, 13), 2025-07-02 00:00:00
Processed HK.06088 89/509, (1960, 13), 2025-07-02 00:00:00
Processed HK.08532 90/509, (1784, 13), 2025-06-30 00:00:00
Processed HK.03333 91/509, (1749, 13), 2024-01-29 00:00:00
Processed HK.00016 92/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00769 93/509, (2454, 13), 2025-06-18 00:00:00
Processed HK.01385 94/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00522 95/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01860 96/509, (1609, 13), 2025-07-02 00:00:00
Processed HK.89988 97/509, (499, 13), 2025-07-02 00:00:00
Processed HK.06883 98/509, (4, 13), 2025-07-02 00:00:00
Processed HK.01060 99/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00960 100/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01132 101/509, (2453, 13), 2025-07-02 00:00:00
Processed HK.01672 102/509, (1701, 13), 2025-07-02 00:00:00
Processed HK.02453 103/509, (362, 13), 2025-07-02 00:00:00
Processed HK.00116 104/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00708 105/509, (2059, 13), 2025-03-31 00:00:00
Processed HK.06606 106/509, (765, 13), 2024-03-27 00:00:00
Processed HK.08452 108/509, (1995, 13), 2025-06-30 00:00:00
Processed HK.02306 109/509, (598, 13), 2025-07-02 00:00:00
Processed HK.00884 110/509, (2340, 13), 2025-07-02 00:00:00
Processed HK.02602 111/509, (674, 13), 2025-07-02 00:00:00
Processed HK.01763 112/509, (1719, 13), 2025-07-02 00:00:00
Processed HK.06127 113/509, (1066, 13), 2025-07-02 00:00:00
Processed HK.02319 114/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00326 115/509, (2451, 13), 2025-07-02 00:00:00
Processed HK.01747 116/509, (1380, 13), 2025-07-02 00:00:00
Processed HK.06110 117/509, (1408, 13), 2025-07-02 00:00:00
Processed HK.08611 118/509, (1646, 13), 2025-07-02 00:00:00
Processed HK.09660 119/509, (168, 13), 2025-07-02 00:00:00
Processed HK.02098 120/509, (2452, 13), 2025-06-30 00:00:00
Processed HK.02477 121/509, (359, 13), 2025-07-02 00:00:00
Processed HK.00853 122/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.09879 123/509, (312, 13), 2025-07-02 00:00:00
Processed HK.01114 124/509, (2088, 13), 2025-07-02 00:00:00
Processed HK.03606 125/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01316 126/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00322 127/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02531 128/509, (237, 13), 2025-07-02 00:00:00
Processed HK.00184 129/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.00285 130/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00921 131/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00165 132/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02076 133/509, (615, 13), 2025-07-02 00:00:00
Processed HK.02438 134/509, (291, 13), 2025-07-02 00:00:00
Processed HK.03939 135/509, (2459, 13), 2025-07-02 00:00:00
Processed HK.00269 136/509, (2035, 13), 2025-07-02 00:00:00
Processed HK.01072 137/509, (2460, 13), 2025-07-02 00:00:00
Processed HK.02727 138/509, (2425, 13), 2025-07-02 00:00:00
Processed HK.00595 139/509, (2456, 13), 2025-07-02 00:00:00
Processed HK.03896 140/509, (611, 13), 2025-07-02 00:00:00
Processed HK.02489 141/509, (371, 13), 2025-07-02 00:00:00
Processed HK.02503 142/509, (362, 13), 2025-07-02 00:00:00
Processed HK.03880 143/509, (2, 13), 2025-07-02 00:00:00
Processed HK.09678 144/509, (2, 13), 2025-07-02 00:00:00
Processed HK.01468 145/509, (2435, 13), 2025-07-02 00:00:00
Processed HK.08133 146/509, (2459, 13), 2025-06-30 00:00:00
Processed HK.02333 147/509, (2460, 13), 2025-07-02 00:00:00
Processed HK.00604 148/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02360 149/509, (1590, 13), 2025-07-02 00:00:00
Processed HK.02018 150/509, (2451, 13), 2025-07-02 00:00:00
Processed HK.02282 151/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02202 152/509, (2452, 13), 2025-07-02 00:00:00
Processed HK.01458 153/509, (2122, 13), 2025-07-02 00:00:00
Processed HK.01171 154/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.02629 155/509, (28, 13), 2025-07-02 00:00:00
Processed HK.06680 156/509, (847, 13), 2025-07-02 00:00:00
Processed HK.02619 157/509, (5, 13), 2025-07-02 00:00:00
Processed HK.01164 158/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00066 159/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.03868 160/509, (1501, 13), 2025-07-02 00:00:00
Processed HK.02688 161/509, (2457, 13), 2025-07-02 00:00:00
Processed HK.02522 162/509, (261, 13), 2025-07-02 00:00:00
Processed HK.00728 164/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00553 165/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.00857 166/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00052 167/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00358 168/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02668 169/509, (2458, 13), 2025-07-02 00:00:00
Processed HK.00017 170/509, (2459, 13), 2025-07-02 00:00:00
Processed HK.02465 171/509, (164, 13), 2025-07-02 00:00:00
Processed HK.00666 172/509, (375, 13), 2025-07-02 00:00:00
Processed HK.01799 173/509, (2336, 13), 2025-07-02 00:00:00
Processed HK.06657 174/509, (241, 13), 2025-07-02 00:00:00
Processed HK.02565 175/509, (26, 13), 2025-07-02 00:00:00
Processed HK.09896 176/509, (729, 13), 2025-07-02 00:00:00
Processed HK.03377 177/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02269 178/509, (1982, 13), 2025-07-02 00:00:00
Processed HK.00169 179/509, (2453, 13), 2025-07-02 00:00:00
Processed HK.02410 180/509, (211, 13), 2025-07-02 00:00:00
Processed HK.03908 181/509, (2371, 13), 2025-07-02 00:00:00
Processed HK.02268 182/509, (396, 13), 2025-07-02 00:00:00
Processed HK.83690 183/509, (499, 13), 2025-07-02 00:00:00
Processed HK.00082 184/509, (2334, 13), 2025-07-02 00:00:00
Processed HK.03998 185/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.06959 186/509, (362, 13), 2025-07-02 00:00:00
Processed HK.01918 187/509, (2211, 13), 2025-07-02 00:00:00
Processed HK.02150 188/509, (983, 13), 2025-07-02 00:00:00
Processed HK.00232 189/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.09866 190/509, (811, 13), 2025-07-02 00:00:00
Processed HK.02443 191/509, (266, 13), 2025-07-02 00:00:00
Processed HK.00267 192/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02515 193/509, (292, 13), 2025-07-02 00:00:00
Processed HK.00020 194/509, (858, 13), 2025-07-02 00:00:00
Processed HK.02097 195/509, (82, 13), 2025-07-02 00:00:00
Processed HK.00717 196/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.03328 197/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00013 198/509, (983, 13), 2025-07-02 00:00:00
Processed HK.00268 199/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00460 200/509, (2297, 13), 2025-07-02 00:00:00
Processed HK.00902 201/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02510 202/509, (162, 13), 2025-07-02 00:00:00
Processed HK.02898 203/509, (270, 13), 2025-06-30 00:00:00
Processed HK.00939 204/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.03690 205/509, (1665, 13), 2025-07-02 00:00:00
Processed HK.00818 206/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.06865 207/509, (2359, 13), 2025-07-02 00:00:00
Processed HK.02419 208/509, (383, 13), 2025-07-02 00:00:00
Processed HK.01919 209/509, (2377, 13), 2025-07-02 00:00:00
Processed HK.03681 210/509, (1385, 13), 2025-07-02 00:00:00
Processed HK.09890 211/509, (430, 13), 2025-07-02 00:00:00
Processed HK.06911 212/509, (311, 13), 2025-07-02 00:00:00
Processed HK.00001 213/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00189 214/509, (2163, 13), 2025-07-02 00:00:00
Processed HK.00012 215/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02603 216/509, (26, 13), 2025-07-02 00:00:00
Processed HK.00008 217/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01099 218/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00489 219/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.02777 220/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.01138 221/509, (2414, 13), 2025-07-02 00:00:00
Processed HK.02611 222/509, (2001, 13), 2025-07-02 00:00:00
Processed HK.02171 223/509, (991, 13), 2025-07-02 00:00:00
Processed HK.01044 224/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02013 225/509, (1588, 13), 2025-07-02 00:00:00
Processed HK.09995 226/509, (1141, 13), 2025-07-02 00:00:00
Processed HK.08529 227/509, (264, 13), 2025-06-30 00:00:00
Processed HK.03900 228/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.01443 229/509, (2461, 13), 2025-06-30 00:00:00
Processed HK.02252 230/509, (899, 13), 2025-07-02 00:00:00
Processed HK.02338 231/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.08637 232/509, (246, 13), 2025-07-02 00:00:00
Processed HK.00780 233/509, (1621, 13), 2025-07-02 00:00:00
Processed HK.06099 234/509, (2146, 13), 2025-07-02 00:00:00
Processed HK.00916 235/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02643 236/509, (5, 13), 2025-07-02 00:00:00
Processed HK.08349 237/509, (1836, 13), 2025-07-02 00:00:00
Processed HK.01038 238/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.01810 239/509, (1718, 13), 2025-07-02 00:00:00
Processed HK.02570 240/509, (137, 13), 2025-07-02 00:00:00
Processed HK.02899 241/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01137 242/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.02400 243/509, (1363, 13), 2025-07-02 00:00:00
Processed HK.00992 244/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01333 245/509, (40, 13), 2025-07-02 00:00:00
Processed HK.01334 246/509, (239, 13), 2025-06-30 00:00:00
Processed HK.01611 247/509, (2111, 13), 2025-07-02 00:00:00
Processed HK.09698 248/509, (1146, 13), 2025-07-02 00:00:00
Processed HK.02487 249/509, (504, 13), 2025-07-02 00:00:00
Processed HK.02460 250/509, (169, 13), 2025-07-02 00:00:00
Processed HK.02519 251/509, (157, 13), 2025-07-02 00:00:00
Processed HK.00558 252/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.03898 253/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02313 254/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.09982 255/509, (698, 13), 2024-03-28 00:00:00
Processed HK.01109 256/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01471 257/509, (220, 13), 2025-06-30 00:00:00
Processed HK.02196 258/509, (2460, 13), 2025-07-02 00:00:00
Processed HK.00288 259/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.01800 260/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.09680 261/509, (240, 13), 2025-07-02 00:00:00
Processed HK.02357 262/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01548 263/509, (2334, 13), 2025-07-02 00:00:00
Processed HK.00136 264/509, (2457, 13), 2025-07-02 00:00:00
Processed HK.01336 265/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02367 266/509, (649, 13), 2025-07-02 00:00:00
Processed HK.01133 267/509, (2458, 13), 2025-07-02 00:00:00
Processed HK.02221 268/509, (2307, 13), 2025-07-02 00:00:00
Processed HK.01698 269/509, (680, 13), 2025-07-02 00:00:00
Processed HK.02208 270/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01415 271/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.01997 272/509, (1865, 13), 2025-07-02 00:00:00
Processed HK.09690 273/509, (432, 13), 2025-07-02 00:00:00
Processed HK.00293 274/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.02469 275/509, (606, 13), 2025-07-02 00:00:00
Processed HK.03738 276/509, (1835, 13), 2025-07-02 00:00:00
Processed HK.00059 277/509, (2384, 13), 2025-03-31 00:00:00
Processed HK.02158 278/509, (1094, 13), 2025-07-02 00:00:00
Processed HK.06881 279/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00881 280/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02556 281/509, (277, 13), 2025-07-02 00:00:00
Processed HK.00981 282/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.01090 283/509, (2462, 13), 2025-06-30 00:00:00
Processed HK.00845 284/509, (2388, 13), 2025-03-31 00:00:00
Processed HK.00860 285/509, (2445, 13), 2025-06-30 00:00:00
Processed HK.06618 286/509, (1120, 13), 2025-07-02 00:00:00
Processed HK.02559 287/509, (247, 13), 2025-07-02 00:00:00
Processed HK.00291 288/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02696 289/509, (1395, 13), 2025-07-02 00:00:00
Processed HK.00966 290/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.03788 291/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.01772 292/509, (1652, 13), 2025-07-02 00:00:00
Processed HK.00998 293/509, (2461, 13), 2025-07-02 00:00:00
Processed HK.02567 294/509, (174, 13), 2025-07-02 00:00:00
Processed HK.01416 295/509, (1043, 13), 2025-07-02 00:00:00
Processed HK.02507 296/509, (238, 13), 2025-07-02 00:00:00
Processed HK.02506 297/509, (123, 13), 2025-07-02 00:00:00
Processed HK.00568 298/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02545 299/509, (245, 13), 2025-07-02 00:00:00
Processed HK.06601 300/509, (1058, 13), 2025-07-02 00:00:00
Processed HK.00316 301/509, (2449, 13), 2025-07-02 00:00:00
Processed HK.01299 302/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.09639 303/509, (178, 13), 2025-07-02 00:00:00
Processed HK.00945 304/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00296 305/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00559 306/509, (2462, 13), 2025-06-30 00:00:00
Processed HK.02779 307/509, (1786, 13), 2025-07-02 00:00:00
Processed HK.06823 308/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00868 309/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02858 310/509, (1871, 13), 2025-07-02 00:00:00
Processed HK.09626 311/509, (1044, 13), 2025-07-02 00:00:00
Processed HK.09999 312/509, (1242, 13), 2025-07-02 00:00:00
Processed HK.01647 313/509, (2023, 13), 2025-07-02 00:00:00
Processed HK.01026 314/509, (2462, 13), 2025-06-30 00:00:00
Processed HK.02549 315/509, (183, 13), 2025-07-02 00:00:00
Processed HK.00011 316/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.06060 317/509, (1906, 13), 2025-07-02 00:00:00
Processed HK.08028 318/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01816 319/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01663 320/509, (2462, 13), 2025-06-30 00:00:00
Processed HK.09888 321/509, (1049, 13), 2025-07-02 00:00:00
Processed HK.00777 322/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.01776 323/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.02359 324/509, (1608, 13), 2025-07-02 00:00:00
Processed HK.06168 325/509, (4, 13), 2025-07-02 00:00:00
Processed HK.00175 326/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.08540 327/509, (1713, 13), 2025-07-02 00:00:00
Processed HK.08606 328/509, (1709, 13), 2025-06-30 00:00:00
Processed HK.02577 329/509, (123, 13), 2025-07-02 00:00:00
Processed HK.01570 330/509, (2216, 13), 2025-06-30 00:00:00
Processed HK.02015 331/509, (953, 13), 2025-07-02 00:00:00
Processed HK.06936 332/509, (144, 13), 2025-07-02 00:00:00
Processed HK.09922 333/509, (1342, 13), 2025-07-02 00:00:00
Processed HK.00005 334/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.00697 335/509, (2463, 13), 2025-07-02 00:00:00
Processed HK.03633 336/509, (2462, 13), 2025-07-02 00:00:00
Processed HK.02350 337/509, (648, 13), 2025-07-02 00:00:00
Processed HK.09985 338/509, (620, 13), 2025-07-02 00:00:00
Processed HK.02238 339/509, (2463, 13), 2025-07-02 00:00:00

In [1]:
# ticker_history[ticker_history['code']=='HK.00700'].shape
ticker_history['code'].drop_duplicates().shape

quote_ctx.close()

NameError: name 'ticker_history' is not defined

In [47]:
def super_trend_daily(row, ticker_history, test=None):
	ticker_id = row['ticker_id']
	data = ticker_history[ticker_history['code'] == ticker_id].reset_index(drop=True)

	row['close'] = None
	row['ticker_name'] = None
	row['supert'] = None
	row['supertl'] = None
	row['supertd'] = None
	row['supertd_prev'] = None

	row['supertd_change'] = None
	row['time_key'] = None

	if data is None or data.empty:
		print(f"Failed to fetch data for {ticker_id}")
		return row


	ticker_name = data.iloc[0]['name'].strip()
	row['ticker_name'] = ticker_name

	SUPERTd = ta.supertrend(high=data['high'], low=data['low'], close=data['close'], length=10, multiplier=3.0, fillna=0.0)

	if SUPERTd is None or SUPERTd.empty:
		print(f"Failed to calculate Supertrend for {ticker_id} | 可能是上市时间太短。 {data.shape}")
		return row
	
	data['supert'] = SUPERTd['SUPERT_10_3.0']
	data['supertl'] = SUPERTd['SUPERTl_10_3.0']
	data['supertd'] = SUPERTd['SUPERTd_10_3.0']

	data['supertd_prev'] = data['supertd'].shift(1)

	data = data.assign(
		supertd_change = 0
	)
	condition = (data['supertd'] > 0) & (data['supertd_prev'] < 0)
	data.loc[condition, 'supertd_change'] = 1

	condition = (data['supertd'] < 0) & (data['supertd_prev'] > 0)
	data.loc[condition, 'supertd_change'] = -1

	last_row = data.iloc[-1]

	message  = ""

	if last_row['supertd_change'] > 0 and last_row['supertd'] > 0 and last_row['close'] > last_row['supertl']:
		message = f"{ticker_id} 向上，买入机会"
	elif last_row['supertd_change'] < 0 and last_row['supertd'] < 0 and last_row['close'] < last_row['supertl']:
		message = f"{ticker_id} 向下，卖出机会"
	elif last_row['supertd'] > 0:
		message = f"{ticker_id} 向上，但需谨慎"
	elif last_row['supertd'] < 0:
		message = f"{ticker_id} 向下，但需谨慎"
	else:
		message = f"{ticker_id} 无明显趋势"
	row['close'] = last_row['close']

	row['supert'] = last_row['supert']
	row['supertl'] = last_row['supertl']
	row['supertd'] = last_row['supertd']
	row['supertd_prev'] = last_row['supertd_prev']
	row['supertd_change'] = last_row['supertd_change']
	row['time_key'] = last_row['time_key']
	return row

In [56]:
def cal_technicals(row, ticker_data_df, test=None):
	ticker_data = ticker_data_df[ticker_data_df['code'] == row['ticker_id']].reset_index(drop=True)

	row['EMA_144_daily'] = None
	row['EMA_169_daily'] = None
	row['SMA_5_Cross_SMA_20'] = 0

	if ticker_data.empty:
		return row
	
	indicators = [
		(talib.EMA, "EMA_13_daily", 13),
		(talib.EMA, "EMA_21_daily", 20),
		(talib.EMA, "EMA_144_daily", 144),
		(talib.EMA, "EMA_169_daily", 169),
		(talib.SMA, "SMA_5_daily", 5),
		(talib.SMA, "SMA_10_daily", 10),
		(talib.SMA, "SMA_20_daily", 20),
		(talib.SMA, "SMA_50_daily", 50),
		(talib.SMA, "SMA_100_daily", 100),
	]

	for func, name, period in indicators:
		ticker_data[name] = func(ticker_data['close'], timeperiod=period)


	ticker_data = ticker_data.assign(SMA_5_Cross_SMA_20=0,)
	ticker_data['SMA_5_daily_prev'] = ticker_data['SMA_5_daily'].shift(1)
	ticker_data['SMA_20_daily_prev'] = ticker_data['SMA_20_daily'].shift(1)

	condition = (ticker_data['SMA_5_daily'] > ticker_data['SMA_20_daily']) & (ticker_data['SMA_5_daily_prev'] < ticker_data['SMA_20_daily_prev'])
	ticker_data.loc[condition, 'SMA_5_Cross_SMA_20'] = 1
	condition = (ticker_data['SMA_5_daily'] < ticker_data['SMA_20_daily']) & (ticker_data['SMA_5_daily_prev'] > ticker_data['SMA_20_daily_prev'])
	ticker_data.loc[condition, 'SMA_5_Cross_SMA_20'] = -1

	ticker_data = ticker_data.drop(columns=['SMA_5_daily_prev', 'SMA_20_daily_prev'])

	last_row = ticker_data.iloc[-1]

	row['EMA_144_daily'] = last_row['EMA_144_daily']
	row['EMA_169_daily'] = last_row['EMA_169_daily']
	row['SMA_5_Cross_SMA_20'] = last_row['SMA_5_Cross_SMA_20']
	row['vegas'] = 0
	if row['close'] > row['EMA_144_daily'] and row['close'] > row['EMA_169_daily']:
		row['vegas'] = 1
	elif row['close'] < row['EMA_144_daily'] and row['close'] < row['EMA_169_daily']:
		row['vegas'] = -1
	return row

In [52]:
df = config_tickers.apply(super_trend_daily, axis=1, args=(ticker_history, None))

print('cal super trend success.')

Failed to calculate Supertrend for HK.02050 | 可能是上市时间太短。 (7, 13)
Failed to calculate Supertrend for HK.02508 | 可能是上市时间太短。 (4, 13)
Failed to calculate Supertrend for HK.06883 | 可能是上市时间太短。 (4, 13)
Failed to fetch data for HK.06613
Failed to calculate Supertrend for HK.03880 | 可能是上市时间太短。 (2, 13)
Failed to calculate Supertrend for HK.09678 | 可能是上市时间太短。 (2, 13)
Failed to calculate Supertrend for HK.02619 | 可能是上市时间太短。 (5, 13)
Failed to fetch data for HK.02592
Failed to calculate Supertrend for HK.02643 | 可能是上市时间太短。 (5, 13)
Failed to calculate Supertrend for HK.06168 | 可能是上市时间太短。 (4, 13)
Failed to calculate Supertrend for HK.03288 | 可能是上市时间太短。 (9, 13)
Failed to calculate Supertrend for HK.02609 | 可能是上市时间太短。 (7, 13)
Failed to calculate Supertrend for HK.06603 | 可能是上市时间太短。 (2, 13)
Failed to fetch data for HK.02915
Failed to calculate Supertrend for HK.02617 | 可能是上市时间太短。 (7, 13)

In [57]:
df = df.apply(cal_technicals, axis=1, args=(ticker_history, None))
print('cal technicals success.')

cal technicals success.

In [61]:
SMA520_df = df[df['SMA_5_Cross_SMA_20'] > 0].reset_index(drop=True)

In [37]:
bull_df = df[(df['supertd'] > 0) & (df['supertd_change'] > 0) & (df['vegas'] > 0)]
bear_df = df[(df['supertd'] < 0) & (df['supertd_change'] < 0) & (df['vegas'] < 0)]

new_ticker_df = df[df['ticker_name'].isnull()]

df = df.dropna(subset=['ticker_name'])   # ticker name为打新股未上市

In [38]:
rev_df = position_df.merge(df, left_on='code', right_on='ticker_id', how='left')
rev_df['prof_rate'] = rev_df['close'] / rev_df['average_cost'] - 1

rev_df = rev_df[['code', 'time_key', 'stock_name', 'average_cost',
		'position_side', 'close', 'prof_rate',
		'market_val', 'supertd', 'supertd_prev', 'supertd_change', 'vegas']]

In [39]:
display(rev_df)

,code,time_key,stock_name,average_cost,position_side,close,prof_rate,market_val,supertd,supertd_prev,supertd_change,vegas
0,HK.03690,2025-07-02 00:00:00,美团-W,132.500,LONG,124.20,-0.062642,62300.0,-1.0,-1.0,0.0,-1.0
1,HK.01788,2025-07-02 00:00:00,国泰君安国际,4.730,LONG,3.47,-0.266385,34600.0,-1.0,-1.0,0.0,1.0
2,HK.01398,2025-07-02 00:00:00,工商银行,6.360,LONG,6.36,0.000000,31650.0,1.0,1.0,0.0,1.0
3,HK.01211,2025-07-02 00:00:00,比亚迪股份,265.600,LONG,122.00,-0.540663,121600.0,-1.0,-1.0,0.0,1.0
4,HK.00700,2025-07-02 00:00:00,腾讯控股,267.338,LONG,502.00,0.877773,141783.0,1.0,1.0,0.0,1.0

In [40]:
display(new_ticker_df)

,EMA_144_daily,EMA_169_daily,close,supert,supertd,supertd_change,supertd_prev,supertl,ticker_id,ticker_name,time_key,vegas
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HK.06613,None,None,NaN
162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HK.02592,None,None,NaN
487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HK.02915,None,None,NaN

In [ ]:
display(bull_df)

,EMA_144_daily,EMA_169_daily,close,supert,supertd,supertd_change,supertd_prev,supertl,ticker_id,ticker_name,time_key,vegas
308,7.540169,7.574390,7.760,7.019796,1.0,1.0,-1.0,7.019796,HK.00868,信义玻璃,2025-07-02 00:00:00,1.0
312,0.078146,0.077746,0.088,0.065619,1.0,1.0,-1.0,0.065619,HK.01647,雄岸科技,2025-07-02 00:00:00,1.0

In [ ]:
display(bear_df)

,EMA_144_daily,EMA_169_daily,close,supert,supertd,supertd_change,supertd_prev,supertl,ticker_id,ticker_name,time_key,vegas
356,73.799255,72.701713,65.000,86.257425,-1.0,-1.0,1.0,0.0,HK.02479,天聚地合,2025-03-31 00:00:00,-1.0
384,0.042531,0.042541,0.037,0.049121,-1.0,-1.0,1.0,0.0,HK.00491,英皇文化产业,2025-07-02 00:00:00,-1.0

In [62]:
display(SMA520_df)

,EMA_144_daily,EMA_169_daily,close,supert,supertd,supertd_change,supertd_prev,supertl,ticker_id,ticker_name,time_key,vegas,SMA_5_Cross_SMA_20
0,0.031930,0.033281,0.024,0.024653,-1.0,0.0,-1.0,0.000000,HK.08532,宝发控股,2025-06-30 00:00:00,-1.0,1
1,0.040342,0.040847,0.048,0.040367,1.0,0.0,1.0,0.040367,HK.01132,橙天嘉禾,2025-07-02 00:00:00,1.0,1
2,0.617460,0.714139,0.380,0.335001,1.0,0.0,1.0,0.335001,HK.02438,出门问问,2025-07-02 00:00:00,-1.0,1
3,5.483593,5.539478,5.000,5.123113,-1.0,0.0,-1.0,0.000000,HK.02202,万科企业,2025-07-02 00:00:00,-1.0,1
4,37.131785,37.264927,35.500,37.463895,-1.0,0.0,-1.0,0.000000,HK.09896,名创优品,2025-07-02 00:00:00,-1.0,1
5,0.453687,0.434801,0.650,0.554588,1.0,0.0,1.0,0.554588,HK.00169,万达酒店发展,2025-07-02 00:00:00,1.0,1
6,26.805130,27.349706,21.150,22.022747,-1.0,0.0,-1.0,0.000000,HK.02410,同源康医药-B,2025-07-02 00:00:00,-1.0,1
7,1.306030,1.364989,1.410,1.140680,1.0,0.0,1.0,1.140680,HK.02150,奈雪的茶,2025-07-02 00:00:00,1.0,1
8,10.229048,10.512169,9.500,8.055602,1.0,0.0,1.0,8.055602,HK.06865,福莱特玻璃,2025-07-02 00:00:00,-1.0,1
9,3.312532,3.250893,3.220,3.443783,-1.0,0.0,-1.0,0.000000,HK.03738,阜博集团,2025-07-02 00:00:00,-1.0,1
10,26.015076,26.235700,25.700,23.792819,1.0,1.0,-1.0,23.792819,HK.00291,华润啤酒,2025-07-02 00:00:00,-1.0,1
11,0.063678,0.062741,0.089,0.070694,1.0,0.0,1.0,0.070694,HK.01416,CTR HOLDINGS,2025-07-02 00:00:00,1.0,1
12,NaN,NaN,15.400,16.399792,-1.0,0.0,-1.0,0.000000,HK.02585,梦金园,2025-07-02 00:00:00,0.0,1
13,0.020732,0.021647,0.020,0.017619,1.0,0.0,1.0,0.017619,HK.00493,国美零售,2025-07-02 00:00:00,-1.0,1
14,2.908026,3.000868,2.650,2.281103,1.0,1.0,-1.0,2.281103,HK.00968,信义光能,2025-07-02 00:00:00,-1.0,1
15,16.769181,16.603306,20.850,21.323986,-1.0,0.0,-1.0,0.000000,HK.00590,六福集团,2025-07-02 00:00:00,1.0,1
16,18.719519,20.619769,14.380,11.664536,1.0,1.0,-1.0,11.664536,HK.01274,知行科技,2025-07-02 00:00:00,-1.0,1
17,616.114601,562.686682,1005.000,834.080636,1.0,0.0,1.0,834.080636,HK.06181,老铺黄金,2025-07-02 00:00:00,1.0,1
18,0.197782,0.198046,0.345,0.289924,1.0,0.0,1.0,0.289924,HK.00399,领航医药生物科技,2025-07-02 00:00:00,1.0,1

In [46]:
df[(df['vegas'] > 0) & (df['supertd'] > 0) & (df['close'] > df['supertl'])].reset_index(drop=True)

,EMA_144_daily,EMA_169_daily,close,supert,supertd,supertd_change,supertd_prev,supertl,ticker_id,ticker_name,time_key,vegas
0,8.012562,7.877448,9.780,8.838706,1.0,0.0,1.0,8.838706,HK.01888,建滔积层板,2025-07-02 00:00:00,1.0
1,6.290089,6.301469,7.590,6.970516,1.0,0.0,1.0,6.970516,HK.00101,恒隆地产,2025-07-02 00:00:00,1.0
2,3.749877,3.904095,4.730,3.813818,1.0,0.0,1.0,3.813818,HK.01911,华兴资本控股,2025-07-02 00:00:00,1.0
3,0.035079,0.035257,0.045,0.033389,1.0,0.0,1.0,0.033389,HK.00279,裕承科金,2025-07-02 00:00:00,1.0
4,6.095045,5.993607,7.940,7.203661,1.0,0.0,1.0,7.203661,HK.01093,石药集团,2025-07-02 00:00:00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
255,0.074226,0.073722,0.093,0.080554,1.0,0.0,1.0,0.080554,HK.01621,域高国际控股,2025-07-02 00:00:00,1.0
256,5.590627,5.537246,6.050,5.738168,1.0,0.0,1.0,5.738168,HK.02386,中石化炼化工程,2025-07-02 00:00:00,1.0
257,469.042063,461.162714,502.000,487.569245,1.0,0.0,1.0,487.569245,HK.00700,腾讯控股,2025-07-02 00:00:00,1.0
258,27.384294,27.326975,29.550,26.589180,1.0,0.0,1.0,26.589180,HK.00772,阅文集团,2025-07-02 00:00:00,1.0
259,2.579752,2.579024,3.670,3.067790,1.0,0.0,1.0,3.067790,HK.02186,绿叶制药,2025-07-02 00:00:00,1.0